tap "homebrew/core"

brew "fasd"
brew "fswatch"
brew "fd"
brew "gh"
brew "git"
brew "nvim"
brew "the_silver_searcher"
brew "vim"
brew "zsh"
brew "zsh-async"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
